spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/StudentNewsDB
    username: postgres
    password: "azor1234"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.mail.ru
    port: 465
    username: "student-news@mail.ru"
    password: "9kdJneg5pYT9ZSZyYten"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
jwt:
  secret: "62A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration: 3600000

token:
  signing:
    key: "TestKeyForStudentNewsService"